IF DB_ID('MyCompany') IS NULL
	CREATE DATABASE MyCompany;
GO
USE MyCompany;
GO
IF NOT EXISTS( SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Employees' )
	CREATE TABLE MyCompany.dbo.Employees
	(
		ID INT IDENTITY(1,1) PRIMARY KEY,
		FirstName VARCHAR(25) NOT NULL,
		LastName VARCHAR(25) NOT NULL,		
		Address VARCHAR(40) NOT NULL,
		City VARCHAR(25) NOT NULL,
		State VARCHAR(25) NOT NULL,
		Country VARCHAR(25) NOT NULL,
		JobTitle VARCHAR(40) NOT NULL,
		JobDepartment VARCHAR(25) NOT NULL,
		ManagerFirstName VARCHAR(25) NOT NULL,
		ManagerLastName VARCHAR(25) NOT NULL
	);
GO
INSERT INTO MyCompany.dbo.Employees (FirstName, LastName, Address, City, State, Country, JobTitle, JobDepartment, ManagerFirstName, ManagerLastName )
VALUES 
	('John', 'Smith', '123 Main St', 'Vallejo', 'California', 'USA', 'Systems Administrator', 'IT', 'Sarah', 'Johnson'),
	('Emily', 'Brown', '456 Elm St', 'Springfield', 'Illinois', 'USA', 'Network Engineer', 'IT', 'David', 'Martinez'),
	('Michael', 'Johnson', '789 Oak St', 'Lakeside', 'Michigan', 'USA', 'Cybersecurity Analyst', 'IT', 'Jessica', 'Williams'),
	('Sarah', 'Garcia', '101 Pine St', 'Mountain View', 'California', 'USA', 'IT Project Manager', 'IT', 'James', 'Lee'),
	('Daniel', 'Rodriguez', '202 Cedar St', 'Riverside', 'Florida', 'USA', 'Database Administrator', 'IT', 'Rebecca', 'Davis'),
	('Jennifer', 'Martinez', '303 Maple St', 'Lexington', 'Kentucky', 'USA', 'IT Support Specialist', 'IT', 'Robert', 'Thompson'),
	('Christopher', 'Nguyen', '404 Birch St', 'Portland', 'Oregon', 'USA', 'Software Developer', 'IT', 'Emily', 'Brown'),
	('Jessica', 'Clark', '505 Walnut St', 'Denver', 'Colorado', 'USA', 'IT Operations Manager', 'IT', 'Michael', 'Johnson'),
	('David', 'Anderson', '606 Spruce St', 'Seattle', 'Washington', 'USA', 'IT Systems Analyst', 'IT', 'Sarah', 'Garcia'),
	('Amanda', 'Wright', '707 Cherry St', 'Orlando', 'Florida', 'USA', 'IT Technician', 'IT', 'Daniel', 'Rodriguez'),
	('Matthew', 'Turner', '808 Pine St', 'Dallas', 'Texas', 'USA', 'IT Security Specialist', 'IT', 'Jennifer', 'Martinez'),
	('Samantha', 'Lewis', '909 Cedar St', 'Houston', 'Texas', 'USA', 'IT Administrator', 'IT', 'Christopher', 'Nguyen'),
	('Andrew', 'Perez', '1010 Elm St', 'Miami', 'Florida', 'USA', 'IT Consultant', 'IT', 'Sarah', 'Garcia'),
	('Lauren', 'Hill', '1111 Oak St', 'San Francisco', 'California', 'USA', 'IT Specialist', 'IT', 'Emily', 'Brown'),
	('Kevin', 'Scott', '1212 Pine St', 'Sacramento', 'California', 'USA', 'IT Analyst', 'IT', 'Michael', 'Johnson'),
	('Elizabeth', 'Carter', '1313 Maple St', 'Atlanta', 'Georgia', 'USA', 'IT Engineer', 'IT', 'Jessica', 'Clark'),
	('Justin', 'King', '1414 Birch St', 'Chicago', 'Illinois', 'USA', 'IT Manager', 'IT', 'Rebecca', 'Davis'),
	('Rachel', 'Wright', '1515 Walnut St', 'Nashville', 'Tennessee', 'USA', 'IT Consultant', 'IT', 'Robert', 'Thompson'),
	('Tyler', 'Evans', '1616 Spruce St', 'Phoenix', 'Arizona', 'USA', 'IT Administrator', 'IT', 'Sarah', 'Garcia'),
	('Megan', 'Morris', '1717 Cedar St', 'Austin', 'Texas', 'USA', 'IT Support Engineer', 'IT', 'Daniel', 'Rodriguez'),
	('Ryan', 'Baker', '1818 Elm St', 'Charlotte', 'North Carolina', 'USA', 'IT Quality Assurance Analyst', 'IT', 'Jennifer', 'Martinez'),
	('Heather', 'Rivera', '1919 Oak St', 'Tampa', 'Florida', 'USA', 'IT Project Coordinator', 'IT', 'Christopher', 'Nguyen'),
	('Joshua', 'Lopez', '2020 Pine St', 'Las Vegas', 'Nevada', 'USA', 'IT Specialist', 'IT', 'Sarah', 'Garcia'),
	('Amber', 'Green', '2121 Maple St', 'New York City', 'New York', 'USA', 'IT Consultant', 'IT', 'Emily', 'Brown'),
	('Nathan', 'Stewart', '2222 Birch St', 'Los Angeles', 'California', 'USA', 'IT Business Analyst', 'IT', 'Michael', 'Johnson'),
	('Melissa', 'Taylor', '2323 Cedar St', 'Houston', 'Texas', 'USA', 'IT Support Specialist', 'IT', 'Robert', 'Thompson'),
	('Brandon', 'Morales', '2424 Elm St', 'Phoenix', 'Arizona', 'USA', 'Systems Administrator', 'IT', 'Sarah', 'Johnson'),
	('Kayla', 'Hughes', '2525 Maple St', 'Seattle', 'Washington', 'USA', 'Network Engineer', 'IT', 'David', 'Martinez'),
	('Kyle', 'Russell', '2626 Oak St', 'Dallas', 'Texas', 'USA', 'Cybersecurity Analyst', 'IT', 'Jess', 'Will'),
	('Hannah', 'Peterson', '2727 Pine St', 'Atlanta', 'Georgia', 'USA', 'IT Project Manager', 'IT', 'James', 'Lee'),
	('Cody', 'Griffin', '2828 Birch St', 'Miami', 'Florida', 'USA', 'Database Administrator', 'IT', 'Reb', 'Dav'),
	('Caroline', 'Reed', '2929 Walnut St', 'Orlando', 'Florida', 'USA', 'IT Support Engineer', 'IT', 'Robert', 'Thompson'),
	('Dylan', 'Alexander', '3030 Cedar St', 'San Francisco', 'California', 'USA', 'Software Developer', 'IT', 'Emily', 'Brown'),
	('Madison', 'Bell', '3131 Elm St', 'Los Angeles', 'California', 'USA', 'IT Operations Manager', 'IT', 'Michael', 'Johnson'),
	('Bradley', 'Gonzales', '3232 Maple St', 'Portland', 'Oregon', 'USA', 'IT Systems Analyst', 'IT', 'Sarah', 'Garcia'),
	('Ashley', 'Parker', '3333 Oak St', 'Chicago', 'Illinois', 'USA', 'IT Technician', 'IT', 'Daniel', 'Rodriguez'),
	('Justin', 'Cruz', '3434 Pine St', 'Denver', 'Colorado', 'USA', 'IT Security Specialist', 'IT', 'Jennifer', 'Martinez'),
	('Kaitlyn', 'Morgan', '3535 Birch St', 'Charlotte', 'North Carolina', 'USA', 'IT Administrator', 'IT', 'Christopher', 'Nguyen'),
	('Connor', 'Howard', '3636 Walnut St', 'Nashville', 'Tennessee', 'USA', 'IT Consultant', 'IT', 'Sarah', 'Garcia'),
	('Lindsay', 'Long', '3737 Cedar St', 'Boston', 'Massachusetts', 'USA', 'IT Specialist', 'IT', 'Emily', 'Brown'),
	('Evan', 'Diaz', '3838 Elm St', 'Austin', 'Texas', 'USA', 'IT Analyst', 'IT', 'Michael', 'Johnson'),
	('Abigail', 'Ward', '3939 Maple St', 'San Diego', 'California', 'USA', 'IT Engineer', 'IT', 'Jessica', 'Clark'),
	('Tyler', 'Perez', '4040 Oak St', 'Las Vegas', 'Nevada', 'USA', 'IT Manager', 'IT', 'Rebecca', 'Davis'),
	('Olivia', 'Foster', '4141 Pine St', 'Houston', 'Texas', 'USA', 'IT Consultant', 'IT', 'Robert', 'Thompson'),
	('Blake', 'Ramirez', '4242 Cedar St', 'Miami', 'Florida', 'USA', 'IT Administrator', 'IT', 'Sarah', 'Garcia'),
	('Brooke', 'Barnes', '4343 Elm St', 'Seattle', 'Washington', 'USA', 'IT Support Engineer', 'IT', 'Daniel', 'Rodriguez'),
	('Jordan', 'Bennett', '4444 Maple St', 'Chicago', 'Illinois', 'USA', 'IT Quality Assurance Analyst', 'IT', 'Jennifer', 'Martinez'),
	('Logan', 'Coleman', '4545 Oak St', 'Denver', 'Colorado', 'USA', 'IT Project Coordinator', 'IT', 'Christopher', 'Nguyen'),
	('Hailey', 'Gomez', '4646 Pine St', 'Los Angeles', 'California', 'USA', 'IT Specialist', 'IT', 'Sarah', 'Garcia'),
	('Tristan', 'Perry', '4747 Cedar St', 'New York City', 'New York', 'USA', 'IT Consultant', 'IT', 'Emily', 'Brown'),
	('Gabriel', 'Hernandez', '4848 Elm St', 'San Francisco', 'California', 'USA', 'IT Business Analyst', 'IT', 'Michael', 'Johnson'),
	('Savannah', 'Watson', '4949 Maple St', 'Seattle', 'Washington', 'USA', 'Systems Administrator', 'IT', 'Sarah', 'Johnson'),
	('Isaac', 'Adams', '5050 Oak St', 'Dallas', 'Texas', 'USA', 'Network Engineer', 'IT', 'David', 'Martinez'),
	('Avery', 'Torres', '5151 Pine St', 'Los Angeles', 'California', 'USA', 'Cybersecurity Analyst', 'IT', 'Jess', 'Will'),
	('Autumn', 'Bryant', '5252 Birch St', 'Miami', 'Florida', 'USA', 'IT Project Manager', 'IT', 'James', 'Lee'),
	('Peyton', 'Fisher', '5353 Walnut St', 'Orlando', 'Florida', 'USA', 'Database Administrator', 'IT', 'Reb', 'Dav'),
	('Blake', 'Wagner', '5454 Cedar St', 'Phoenix', 'Arizona', 'USA', 'IT Support Engineer', 'IT', 'Robert', 'Thompson'),
	('Evelyn', 'Holmes', '5555 Elm St', 'San Francisco', 'California', 'USA', 'Software Developer', 'IT', 'Emily', 'Brown'),
	('Cole', 'Reyes', '5656 Maple St', 'Los Angeles', 'California', 'USA', 'IT Operations Manager', 'IT', 'Michael', 'Johnson'),
	('Maya', 'Pearson', '5757 Oak St', 'Chicago', 'Illinois', 'USA', 'IT Systems Analyst', 'IT', 'Sarah', 'Garcia'),
	('Owen', 'West', '5858 Pine St', 'Denver', 'Colorado', 'USA', 'IT Technician', 'IT', 'Daniel', 'Rodriguez'),
	('Aria', 'Cole', '5959 Birch St', 'Austin', 'Texas', 'USA', 'IT Security Specialist', 'IT', 'Jennifer', 'Martinez'),
	('Landon', 'Harrison', '6060 Walnut St', 'Charlotte', 'North Carolina', 'USA', 'IT Administrator', 'IT', 'Christopher', 'Nguyen'),
	('Nora', 'Gordon', '6161 Cedar St', 'Nashville', 'Tennessee', 'USA', 'IT Consultant', 'IT', 'Sarah', 'Garcia'),
	('Eli', 'Jenkins', '6262 Elm St', 'Boston', 'Massachusetts', 'USA', 'IT Specialist', 'IT', 'Emily', 'Brown'),
	('Claire', 'Mendoza', '6363 Maple St', 'Los Angeles', 'California', 'USA', 'IT Analyst', 'IT', 'Michael', 'Johnson'),
	('Asher', 'Castillo', '6464 Oak St', 'San Diego', 'California', 'USA', 'IT Engineer', 'IT', 'Jessica', 'Clark'),
	('Adeline', 'Riley', '6565 Pine St', 'Las Vegas', 'Nevada', 'USA', 'IT Manager', 'IT', 'Rebecca', 'Davis'),
	('Henry', 'Stevens', '6666 Birch St', 'Houston', 'Texas', 'USA', 'IT Consultant', 'IT', 'Robert', 'Thompson'),
	('Maria', 'Herrera', '6767 Elm St', 'Miami', 'Florida', 'USA', 'IT Administrator', 'IT', 'Sarah', 'Garcia'),
	('Gavin', 'Sullivan', '6868 Maple St', 'Seattle', 'Washington', 'USA', 'IT Support Engineer', 'IT', 'Daniel', 'Rodriguez'),
	('Clara', 'Burns', '6969 Oak St', 'Chicago', 'Illinois', 'USA', 'IT Quality Assurance Analyst', 'IT', 'Jennifer', 'Martinez'),
	('Leo', 'Wells', '7070 Pine St', 'Denver', 'Colorado', 'USA', 'IT Project Coordinator', 'IT', 'Christopher', 'Nguyen'),
	('Ruby', 'Fuller', '7171 Birch St', 'Los Angeles', 'California', 'USA', 'IT Specialist', 'IT', 'Sarah', 'Garcia'),
	('Julian', 'Bowman', '7272 Elm St', 'New York City', 'New York', 'USA', 'IT Consultant', 'IT', 'Emily', 'Brown'),
	('Elena', 'Patterson', '7373 Maple St', 'San Francisco', 'California', 'USA', 'IT Business Analyst', 'IT', 'Michael', 'Johnson'),
	('Dominic', 'Coleman', '7474 Oak St', 'Seattle', 'Washington', 'USA', 'Systems Administrator', 'IT', 'Sarah', 'Johnson'),
	('Eva', 'Duncan', '7575 Pine St', 'Dallas', 'Texas', 'USA', 'Network Engineer', 'IT', 'David', 'Martinez'),
	('Max', 'Wallace', '7676 Birch St', 'Los Angeles', 'California', 'USA', 'Cybersecurity Analyst', 'IT', 'Jess', 'Will'),
	('Brianna', 'Hunt', '7777 Elm St', 'Miami', 'Florida', 'USA', 'IT Project Manager', 'IT', 'James', 'Lee'),
	('Chase', 'Barnes', '7878 Walnut St', 'Orlando', 'Florida', 'USA', 'Database Administrator', 'IT', 'Reb', 'Dav'),
	('Lila', 'Williamson', '7979 Cedar St', 'Phoenix', 'Arizona', 'USA', 'IT Support Engineer', 'IT', 'Robert', 'Thompson'),
	('Jaxon', 'Hudson', '8080 Maple St', 'San Francisco', 'California', 'USA', 'Software Developer', 'IT', 'Emily', 'Brown'),
	('Isabelle', 'Bishop', '8181 Oak St', 'Los Angeles', 'California', 'USA', 'IT Operations Manager', 'IT', 'Michael', 'Johnson'),
	('Cole', 'Hansen', '8282 Pine St', 'Chicago', 'Illinois', 'USA', 'IT Systems Analyst', 'IT', 'Sarah', 'Garcia'),
	('Amelia', 'Knight', '8383 Birch St', 'Denver', 'Colorado', 'USA', 'IT Technician', 'IT', 'Daniel', 'Rodriguez'),
	('Parker', 'Myers', '8484 Elm St', 'Austin', 'Texas', 'USA', 'IT Security Specialist', 'IT', 'Jennifer', 'Martinez'),
	('Violet', 'Gregory', '8585 Walnut St', 'Charlotte', 'North Carolina', 'USA', 'IT Administrator', 'IT', 'Christopher', 'Nguyen'),
	('Eliana', 'Gibson', '8686 Cedar St', 'Nashville', 'Tennessee', 'USA', 'IT Consultant', 'IT', 'Sarah', 'Garcia'),
	('Xavier', 'Ramsey', '8787 Oak St', 'Boston', 'Massachusetts', 'USA', 'IT Specialist', 'IT', 'Emily', 'Brown'),
	('Miles', 'Wade', '8888 Maple St', 'Los Angeles', 'California', 'USA', 'IT Analyst', 'IT', 'Michael', 'Johnson'),
	('Sophie', 'Hayes', '8989 Pine St', 'San Diego', 'California', 'USA', 'IT Engineer', 'IT', 'Jessica', 'Clark'),
	('Lucas', 'Brewer', '9090 Birch St', 'Las Vegas', 'Nevada', 'USA', 'IT Manager', 'IT', 'Rebecca', 'Davis'),
	('Adalyn', 'Keller', '9191 Elm St', 'Houston', 'Texas', 'USA', 'IT Consultant', 'IT', 'Robert', 'Thompson'),
	('Silas', 'Mendez', '9292 Maple St', 'Miami', 'Florida', 'USA', 'IT Administrator', 'IT', 'Sarah', 'Garcia'),
	('Mila', 'Larson', '9393 Oak St', 'Seattle', 'Washington', 'USA', 'IT Support Engineer', 'IT', 'Daniel', 'Rodriguez'),
	('Zoe', 'Woods', '9494 Pine St', 'Chicago', 'Illinois', 'USA', 'IT Quality Assurance Analyst', 'IT', 'Jennifer', 'Martinez'),
	('Elliot', 'Vargas', '9595 Birch St', 'Denver', 'Colorado', 'USA', 'IT Project Coordinator', 'IT', 'Christopher', 'Nguyen'),
	('Leah', 'Fernandez', '9696 Elm St', 'Los Angeles', 'California', 'USA', 'IT Specialist', 'IT', 'Sarah', 'Garcia'),
	('Hudson', 'Spencer', '9797 Maple St', 'New York City', 'New York', 'USA', 'IT Consultant', 'IT', 'Emily', 'Brown');
GO